<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>IVZVision.Core</RootNamespace>
    <AssemblyName>IVZVision.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>
